# Setup
title:               'The Occasional Pamphlet'
tagline:             '...on scholarly communication'
description:         'The occasional pamphlet from the virtual writing-desk of Stuart Shieber, on scholarly communication and other topics.'
url:		     'https://shieber.github.io'
baseurl:             '/pmphlt'
paginate:            5
permalink:           /:year/:month/:day/:title/

# About/contact
author:
  name:              Stuart Shieber
  url:               https://stuartshieber.com/

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0

# Comments
disqus:
  shortname: pmphlt
# default to true on posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true